# Generated by Django 3.1.2 on 2020-10-12 05:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domainName', models.CharField(max_length=50, verbose_name='Fully qualified domain name')),
                ('ipaddress', models.GenericIPAddressField(default='', unique=True, verbose_name='IPv4 address')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objectSid', models.CharField(max_length=50, verbose_name='Security identifier')),
                ('sAMAccountName', models.CharField(max_length=20, verbose_name='Group name')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objectSid', models.CharField(max_length=50, verbose_name='Security identifier')),
                ('userPrincipalName', models.CharField(max_length=50, verbose_name='User logon name')),
                ('givenName', models.CharField(default='', max_length=30, verbose_name='First name')),
                ('sn', models.CharField(default='', max_length=50, verbose_name='Last name')),
                ('pwdLastSet', models.BooleanField(default=True, verbose_name='Force password change on next logon')),
                ('domains', models.ManyToManyField(to='backend.Domain')),
            ],
        ),
    ]
