# Generated by Django 3.1.2 on 2020-11-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ServerObjectGuid')),
                ('domain', models.CharField(max_length=50, unique=True, verbose_name='Domain')),
                ('host_name', models.CharField(max_length=50, verbose_name='HostName')),
                ('ipv4address', models.GenericIPAddressField(unique=True, verbose_name='IPv4Address')),
            ],
        ),
    ]
