# Generated by Django 3.1.2 on 2020-11-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='acc_admin',
            field=models.CharField(default='a', max_length=50, verbose_name='Account Administrator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domain',
            name='password',
            field=models.CharField(default='b', max_length=100, verbose_name='Admin Password'),
            preserve_default=False,
        ),
    ]
