# Generated by Django 3.1.2 on 2020-11-05 15:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201101_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UserID')),
                ('sam_account_name', models.CharField(max_length=50, verbose_name='SamAccountName')),
                ('user_principal_name', models.CharField(max_length=50, verbose_name='User Principal Name')),
                ('given_name', models.CharField(max_length=50, verbose_name='GivenName')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('domains', models.ManyToManyField(to='backend.Domain')),
            ],
        ),
    ]
