# Generated by Django 3.1.2 on 2020-10-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='computerName',
            field=models.CharField(default='', max_length=50, verbose_name='Computer name'),
        ),
    ]
