# Generated by Django 3.1.2 on 2020-10-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_domain_computername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domainName',
            field=models.CharField(max_length=50, unique=True, verbose_name='Fully qualified domain name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='objectSid',
            field=models.CharField(max_length=50, unique=True, verbose_name='Security identifier'),
        ),
    ]
