# Generated by Django 3.1.2 on 2020-11-05 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainUser',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ObjectGUID')),
                ('sam_account_name', models.CharField(max_length=50, verbose_name='SamAccountName')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.domain')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='domain_users',
            field=models.ManyToManyField(to='backend.DomainUser'),
        ),
    ]
