# Generated by Django 3.1.2 on 2020-11-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_domainuser_distinguished_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='q', max_length=50, verbose_name='Account Password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='domain_users',
            field=models.ManyToManyField(blank=True, to='backend.DomainUser'),
        ),
    ]
