# Generated by Django 3.1.2 on 2020-11-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20201108_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='account_password',
        ),
    ]
