# Generated by Django 3.1.2 on 2020-11-14 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20201108_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainuser',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
    ]
