# Generated by Django 3.1.2 on 2020-11-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_domainuser_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_principal_name',
        ),
        migrations.AddField(
            model_name='domainuser',
            name='user_principal_name',
            field=models.CharField(default=None, max_length=50, verbose_name='User Principal Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sam_account_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='SamAccountName'),
        ),
    ]
