# Generated by Django 3.1.2 on 2020-12-06 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20201118_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainOrganizationalUnit',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ObjectGuid')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('distinguished_name', models.CharField(max_length=100, verbose_name='Distinguished Name')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.domain')),
            ],
        ),
        migrations.CreateModel(
            name='DomainGroup',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ObjectGuid')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('distinguished_name', models.CharField(max_length=100, verbose_name='Distinguished Name')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.domain')),
            ],
        ),
    ]
