# Generated by Django 3.1.2 on 2020-12-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_domaingroup_domainorganizationalunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaingroup',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domaingroup',
            name='display_name',
            field=models.CharField(default='', max_length=50, verbose_name='Display Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domaingroup',
            name='group_category',
            field=models.CharField(default='', max_length=50, verbose_name='Group Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domaingroup',
            name='group_scope',
            field=models.CharField(default='', max_length=50, verbose_name='Group Scope'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domaingroup',
            name='sam_account_name',
            field=models.CharField(default='', max_length=50, verbose_name='SamAccountName'),
            preserve_default=False,
        ),
    ]
