# Generated by Django 3.1.2 on 2020-12-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20201209_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaingroup',
            name='display_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Display Name'),
        ),
    ]
