# Generated by Django 3.1.2 on 2020-12-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20201209_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaingroup',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
