# Generated by Django 3.1.2 on 2020-12-12 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20201209_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UserID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('sam_account_name', models.CharField(max_length=50, unique=True, verbose_name='SamAccountName')),
                ('group_category', models.IntegerField(verbose_name='GroupCategory')),
                ('group_scope', models.IntegerField(verbose_name='GroupScope')),
                ('display_name', models.CharField(blank=True, max_length=50, verbose_name='DisplayName')),
                ('description', models.CharField(blank=True, max_length=50, verbose_name='Description')),
                ('domain_groups', models.ManyToManyField(blank=True, to='backend.DomainGroup')),
            ],
        ),
    ]
