# Generated by Django 3.1.2 on 2020-12-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20201212_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainuser',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
    ]
