# Generated by Django 3.1.2 on 2020-12-15 15:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20201212_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='domain_users',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(null=True, to='backend.Group'),
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UserID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('distinguished_name', models.CharField(max_length=50, verbose_name='Distinguished Name')),
                ('domain_ous', models.ManyToManyField(null=True, to='backend.DomainOrganizationalUnit')),
            ],
        ),
    ]
