# Generated by Django 3.1.2 on 2020-12-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20201215_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaingroup',
            name='created_by_app',
            field=models.BooleanField(default=False, verbose_name='Created by app'),
        ),
        migrations.AddField(
            model_name='domainorganizationalunit',
            name='created_by_app',
            field=models.BooleanField(default=False, verbose_name='Created by app'),
        ),
        migrations.AddField(
            model_name='domainuser',
            name='created_by_app',
            field=models.BooleanField(default=False, verbose_name='Created by app'),
        ),
    ]
