# Generated by Django 3.1.2 on 2020-12-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20201216_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='distinguished_name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='DistinguishedName'),
            preserve_default=False,
        ),
    ]
