# Generated by Django 3.1.2 on 2020-12-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_domain_distinguished_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalunit',
            name='distinguished_name',
        ),
    ]
