# Generated by Django 3.1.2 on 2021-01-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_remove_organizationalunit_distinguished_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='organizational_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.organizationalunit'),
        ),
    ]
