# Generated by Django 3.1.2 on 2021-01-02 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_group_organizational_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='organizational_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.organizationalunit'),
        ),
    ]
