# Generated by Django 3.1.2 on 2021-01-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20210105_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domains',
            field=models.ManyToManyField(blank=True, to='backend.Domain'),
        ),
    ]
