# Generated by Django 3.1.2 on 2021-01-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20210105_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organizational_units',
            field=models.ManyToManyField(blank=True, to='backend.OrganizationalUnit'),
        ),
    ]
