# Generated by Django 3.1.2 on 2021-01-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_user_organizational_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='domain_groups',
            field=models.ManyToManyField(blank=True, related_name='domain_groups', to='backend.DomainGroup'),
        ),
    ]
