# Generated by Django 3.1.2 on 2021-01-07 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20210106_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaingroup',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.group'),
        ),
        migrations.AddField(
            model_name='domainorganizationalunit',
            name='ou_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.organizationalunit'),
        ),
    ]
