# Generated by Django 3.1.2 on 2021-01-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_auto_20210108_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='domain_groups',
        ),
    ]
