# Generated by Django 3.1.2 on 2021-01-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_remove_organizationalunit_domain_ous'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='password',
            new_name='key_name',
        ),
    ]
