# Generated by Django 3.1.2 on 2021-01-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_auto_20210110_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainuser',
            name='distinguished_name',
            field=models.CharField(max_length=100, verbose_name='Distinguished Name'),
        ),
    ]
